### ISSUE TITLE
AttributeError Due to Incorrect Type Handling in parse_transform Function

### ISSUE THREAD

**Issue by tacxou** [RICHARD-Quentin/DataWeaver#1]
### Is there an existing issue that is already proposing this?
- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it
Cast to string failed for value "[ 'Address X', null, 'City Y' ]" (type Array) at path postalAddress.

```yml
etd.json:
  mapping:
    inetOrgPerson.postalAddress:
    - "adresse"
    - "CP"
    - "Ville"
  transforms:
    inetOrgPerson.postalAddress: "join(delimiter=',')"
```
In this case, the postal code is null. If one of the fields is null, the transformer is unable to convert the array into a string.
